---
exclude_paths:
  - echo/*
  - echo/**/*
  - example/*
  - example/**/*
  - notification_visuals/*
  - notification_visuals/**/*
  - size_check/*
  - size_check/**/*
  - test_app/*
  - test_app/**/*
  - build/*
  - build/**/*
  - docs/*
  - docs/**/*
  - .gradle/*
  - .gradle/**/*
  - .idea/*
  - .idea/**/*
  - src/main/java/io/teak/sdk/json/* # Not our code, vendored JSONObject and friends
  - src/main/java/io/teak/sdk/json/**/*
  - src/main/java/io/teak/sdk/shortcutbadger/* # Not our code, vendored ShortcutBadger
  - src/main/java/io/teak/sdk/shortcutbadger/**/*
