#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

brew tap caskroom/cask

# TODO: Ensure both Brew and Caskroom are set up.
if [ "$(which java)" == "" ]; then
  echo "ERROR: Install JDK first.  Maybe use 'brew cask install java'.  Leaving this to you in case you want to handle this differently."
  exit 1
fi

if [ "$(which ant)" == "" ]; then brew install ant; fi
if [ "$(which mvn)" == "" ]; then brew install maven; fi
if [ "$(which android)" == "" ]; then
  brew cask install android-sdk
fi

if [ "$(which sentry-cli)" == "" ]; then brew install getsentry/tools/sentry-cli; fi

ANDROID_HOME=/usr/local/share/android-sdk
export ANDROID_HOME
