version: 2.1

orbs:
  teak: teak/sdk-utils@0.0.3

jobs:
  build:
    docker:
      - image: circleci/android:api-28
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run:
          name: Check for any usage of the org.json.* namespace
          command: ./org_json_check
      - restore_cache:
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Fix 'sdk.dir' in 'local.properties'
          command: |
            echo 'sdk.dir=/opt/android/sdk' > local.properties
            echo 'sdk.dir=/opt/android/sdk' > test_app/local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: ./gradlew assemble
      - run:
          name: Compute Checksum
          command: |
            sha512sum build/outputs/aar/teak-release.aar > teak-release.sha512
            sha256sum build/outputs/aar/teak-release.aar > teak-release.sha256
      - persist_to_workspace:
          root: .
          paths:
            - build/outputs/aar/teak-release.aar
            - teak-release.sha512
            - teak-release.sha256
      - sentry_persist_proguard
      - run:
          name: Make sure we're not using Executors or Threads
          command: ./check_thread_use
      - run:
          name: Run Teak SDK Unit Tests
          command: (cd test_app; ./gradlew test --continue)
      - store_test_results:
          path: test_app/app/build/test-results/

  tag_build:
    docker:
      - image: circleci/android:api-28
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - teak/tag-promote:
          fingerprint: "31:0a:6a:16:60:51:96:90:df:b9:52:86:a9:88:ce:18"

  deploy_versioned:
    docker:
      - image: circleci/android:api-28
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - attach_workspace:
          at: .
      - sentry_upload_proguard
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak-$(git describe --tags --always).aar --acl public-read
            aws s3 cp teak-release.sha512 s3://teak-build-artifacts/android/teak-$(git describe --tags --always).sha512 --acl public-read
            aws s3 cp teak-release.sha256 s3://teak-build-artifacts/android/teak-$(git describe --tags --always).sha256 --acl public-read

  deploy_latest:
    docker:
      - image: circleci/android:api-28
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - attach_workspace:
          at: .
      - sentry_upload_proguard
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak.aar --acl public-read
            aws s3 cp teak-release.sha256 s3://teak-build-artifacts/android/teak.sha256 --acl public-read
            aws s3 cp teak-release.sha512 s3://teak-build-artifacts/android/teak.sha512 --acl public-read

workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build

  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - tag_build:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

commands:
  #
  # Persist ProGuard mappings to workspace
  #
  sentry_persist_proguard:
    description: "Persist ProGuard Mappings to Workspace"
    parameters:
      android_manifest:
        type: string
        default: "build/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml"
      proguard_mapping:
        type: string
        default: "build/outputs/mapping/release/mapping.txt"
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.android_manifest >>
            - << parameters.proguard_mapping >>
  #
  # Upload ProGuard mappings to Sentry
  #
  sentry_upload_proguard:
    description: "Upload ProGuard Mappings to Sentry"
    parameters:
      android_manifest:
        type: string
        default: "build/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml"
      proguard_mapping:
        type: string
        default: "build/outputs/mapping/release/mapping.txt"
    steps:
      - run:
          name: Upload ProGuard Mappings to Sentry
          command: sentry-cli upload-proguard --android-manifest << parameters.android_manifest >> << parameters.proguard_mapping >>
