version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run:
          name: Check for any usage of the org.json.* namespace
          command: ./org_json_check
      - restore_cache:
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Fix 'sdk.dir' in 'local.properties'
          command: |
            echo 'sdk.dir=/opt/android/sdk' > local.properties
            echo 'sdk.dir=/opt/android/sdk' > test_app/local.properties
            echo 'sdk.dir=/opt/android/sdk' > size_check/local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: ./gradlew assemble
      - persist_to_workspace:
          root: build/
          paths:
            - distributions/teak-release.zip
            - outputs/aar/teak-release.aar
            - intermediates/manifests/full/release/AndroidManifest.xml
      # - run:
      #     name: Check the added size of SDK in bytes and methods
      #     command: ./check_size
      - run:
          name: Run Teak SDK Unit Tests
          command: (cd test_app; ./gradlew test)
      - store_test_results:
          path: test_app/app/build/test-results/
  deploy:
    docker:
      - image: circleci/android:api-26-alpha
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: build/
      - run:
          name: Upload ProGuard Mappings to Sentry
          command: sentry-cli upload-proguard --android-manifest build/intermediates/manifests/full/release/AndroidManifest.xml build/outputs/mapping/release/mapping.txt
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/distributions/teak-release.zip s3://teak-build-artifacts/android/teak-$(git describe --tags --always).zip --acl public-read
            aws s3 cp build/distributions/teak-release.zip s3://teak-build-artifacts/android/teak.zip --acl public-read
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak-$(git describe --tags --always).aar --acl public-read
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak.aar --acl public-read
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
