version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run:
          name: Check for any usage of the org.json.* namespace
          command: ./org_json_check
      #- run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Fix 'sdk.dir' in 'local.properties'
          command: |
            echo 'sdk.dir=/opt/android/sdk' > local.properties
            echo 'sdk.dir=/opt/android/sdk' > test_app/local.properties
            echo 'sdk.dir=/opt/android/sdk' > size_check/local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}
      - run:
          name: Build Teak SDK
          command: ./gradlew assemble
      # - run:
      #     name: Check the added size of SDK in bytes and methods
      #     command: ./check_size
      - run:
          name: Run Teak SDK Unit Tests
          command: (cd test_app; ./gradlew test)
  deploy:
    docker:
      - image: circleci/android:api-26-alpha
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - run:
        name: Test?
        command: echo 'It worked I guess.'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [master, /hotfix.*/]
