#!/bin/bash

# Clear previous
adb devices | while read line
do
if [ ! "$line" = "" ] && [ `echo $line | awk '{print $2}'` = "device" ]
then
    device=`echo $line | awk '{print $1}'`
    adb -s $device  shell rm -r /sdcard/test-screenshots/teak-test_deeplink.png &> /dev/null
fi
done

./gradlew clean connectedDebugAndroidTest

adb devices | while read line
do
if [ ! "$line" = "" ] && [ `echo $line | awk '{print $2}'` = "device" ]
then
    device=`echo $line | awk '{print $1}'`
    mkdir -p devices/$device
    (cd devices/$device;
        adb -s $device pull /sdcard/test-screenshots/teak-test_deeplink.png
    )
fi
done
